on:
  push:
  release:
    types: [published]
name: Build and Test Workflow, Publish only in Release
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Npm Install
        run: npm install
      - name: Test
        run: npm run coverage:test
      - name: Publish coverage
        if: github.event_name == 'release'
        run: npm run coverage:publish
      - name: Npm Login and Publish
        if: github.event_name == 'release'
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
          npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}